version: '3'
services:
    bcb:
        image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
        ports: 
            - 8082:8082
    erp-itau:
        image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
        ports: 
            - 9091:9091
    postgres-keymanager:
        image: 'postgres:alpine'
        volumes:
        - postgres-keymanager-volume:/var/lib/postgresql/data
        ports:
          - 5432:5432
        environment:
          POSTGRES_USER: keymanager
          POSTGRES_PASSWORD: keymanager
          POSTGRES_DB: keymanager
          POSTGRES_HOST: postgres-keymanager
 
volumes:
    postgres-keymanager-volume: